[package]
name = "discretionary_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.16", features = ["derive"] }
dirs = "5.0.1"
hex = "0.4.3"
reqwest = { verson = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
sha2 = "0.10.8"
hmac = "0.12.1"
chrono = "0.4.31"
serde_json = "1.0.111"
serde_urlencoded = "0.7.1"
url = "2.5.0"
